name: osm_flutter

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout

jobs:
  publish:
    runs-on: ubuntu-latest
    container:
      image:  python:3
      #image:  google/dart:latest
    steps:
      - uses: actions/checkout@v3
      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests
      - uses: dart-lang/setup-dart@v1
      - name: Install Flutter SDK
        uses: britannio/action-install-flutter@v1
      - run: dart --version
      - run: flutter --version
      - name: preparation release
        run: python check_pubspec_release.py
      - name: clear before release
        run: |
          rm -f *.gif
          rm -rf assets/dynamic-styles.zip
          rm -rf assets/osm-style.zip
          rm -rf flutter_osm_interface
          rm -rf flutter_osm_web
          rm -f check_pubspec_release.py
      - name: fomarting files
        run : dart format .
      - name: Publish package
        run:  flutter pub publish -f